# This is the configuration file for the Powerline Pills Theme for ZSH

# Color codes:
# 0  - Black
# 1  - Red
# 2  - Green
# 3  - Yellow
# 4  - Blue
# 5  - Magenta
# 6  - Cyan
# 7  - White
# 8  - Gray
# 9  - Light Red
# 10 - Light Green
# 11 - Light Yellow
# 12 - Light Blue
# 13 - Light Magenta
# 14 - Light Cyan
# (If you have the ZSH-256color plugin installed, you can use any of the 256 colors.)

# Base
base:
  powerline_icon_right: ''
  powerline_icon_left: ''
  color: 255
  left_top: ['os', 'user', 'folder']
  right_top: ['ruby', 'git', 'time']
  left_bottom: ['cmd']
# OS Info
os:
  background_color: 255
  color: 0
  icon_linux: '🐧'
  icon_darwin: ''
# Username
user:
  background_color: 228
  color: 218
  icon:
    char: '♥'
    color: 218
# Folder
folder:
  background_color: 255
  color: 8
  icon:
    char: '📂'
    color: 255
# Git
git:
  background_color: 105
  color: 255
  icon:
    # Branch icon
    char: ''
    color: 255
    # Uncommited changes
    char_dirty: '!'
    color_dirty: 215
# Date
date:
  background_color: 87
  color: 7
  icon:
    char: '📅'
    color: 7
  # Follows the bash `date` format
  format: '%d/%m/%y'
# Time
time:
  background_color: 87
  color: 18
  icon:
    char: '🕑'
    color: 18
  # Follows the bash `date` format
  format: '%H:%M:%S'
# CMD
cmd:
  background_color_failed: 198
  color_failed: 255
  background_color_success: 158
  color_success: 255
  icon:
    char: '$'
# Ruby version
ruby:
  background_color: 88
  color: 255
  icon:
    char: '💎 '
    color: 15
